[Database]
folder_1_active=true
folder_1_path=/home
folder_1_one_file_system=false
folder_1_monitor=true
folder_1_scan_after_launch=true
folder_1_rescan_after=0
folder_2_active=true
folder_2_path=/mnt
folder_2_one_file_system=false
folder_2_monitor=true
folder_2_scan_after_launch=true
folder_2_rescan_after=0
exclude_1_active=true
exclude_1_type=fixed
exclude_1_pattern=/.snapshots
exclude_1_match_scope=full_path
exclude_1_target=folders
exclude_2_active=true
exclude_2_type=fixed
exclude_2_pattern=/proc
exclude_2_match_scope=full_path
exclude_2_target=folders
exclude_3_active=true
exclude_3_type=fixed
exclude_3_pattern=/sys
exclude_3_match_scope=full_path
exclude_3_target=folders
exclude_hidden_files_and_folders=false
